# Generated by Django 5.2.3 on 2025-07-01 04:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_body"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="body",
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Brief description about your photography business",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_title",
            field=models.CharField(
                default="About StatusKuo",
                help_text="Title for the about section",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="homepage",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_image_1",
            field=models.ForeignKey(
                blank=True,
                help_text="First featured photograph",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="featured_image_2",
            field=models.ForeignKey(
                blank=True,
                help_text="Second featured photograph",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Large hero background image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle",
            field=models.CharField(
                blank=True,
                help_text="Subtitle text below the main headline",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                default="Capturing Life's Perfect Moments",
                help_text="Main headline for the hero section",
                max_length=255,
            ),
        ),
    ]
